{
  "headers": {
    "access-control-allow-credentials": "true",
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "",
    "cache-control": "max-age=0, private, must-revalidate",
    "content-length": "346",
    "content-type": "application/json; charset=utf-8",
    "cross-origin-window-policy": "deny",
    "date": "Mon, 10 Jul 2023 15:22:54 GMT",
    "server": "Fly/a0b91024 (2023-06-13)",
    "x-content-type-options": "nosniff",
    "x-download-options": "noopen",
    "x-frame-options": "SAMEORIGIN",
    "x-permitted-cross-domain-policies": "none",
    "x-ratelimit-limit": "1800",
    "x-ratelimit-remaining": "1799",
    "x-ratelimit-reset": "1689004800",
    "x-request-from": "99.250.61.121",
    "x-request-id": "F3CK5MCAv36qGuAdv8ah",
    "x-request-regions": "a/lga;s/yyz",
    "x-response-origin": "7a6751d7-34a3-6aa6-1ba9-ae0b28e76e78",
    "x-runtime": "232\ufffd\ufffds",
    "x-xss-protection": "1; mode=block",
    "via": "1.1 fly.io",
    "fly-request-id": "01H506C1FD6NG3FADE5FFWJ94Q-lga"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}